### ISSUE TITLE
[Datasource]: Add executed data to DatasourceRegistry

### ISSUE THREAD

**Issue by khusseini** [khusseini/PimcoreRadBrickBundle#20]
In order to retrieve preexecuted data from the DatasourcesRegistry, a few methods should be added:
- `DatasourcesRegistry::hasData(string $name): bool`
- `DatasourcesRegistry::getData(string $name, bool $execute = false, array $execArgs = [])`

This allows for configurations like such:
```
areabricks:
   dummy:
     datasources:
        tags: ~
        products:
          conditions:
            - "datasources.hasData('tags')"
          args:
          - "datasources.getData('tags')"
```
