### ISSUE TITLE
Improve use of existing Symfony Service

### ISSUE THREAD

**Issue by khusseini** [khusseini/PimcoreRadBrickBundle#23]
Currently the use for an existing Symfony Service as the basis for an areabrick is broken.
The definition will always result in the same, non-configurable areabrick, however the arebrick classes are meant to be "templates".
For example a registration_form arebrick:

```yaml
pimcore_rad_brick:
  areabricks:
    registration_form:
      class: 'app.areabricks.form'
     options:
       type: '\App\Forms\RegistrationType'
```

```php

use Khusseini\PimcoreRadBrickBundle\Areabricks\AbstractAreabrick;

class FormAreabrick extends AbstractAreabrick
{
    /// Handle injections in __constructor

    public function configure(array $options) {
        // process options here
    }

    public function doAction(Info $info): ?Response
    {
        // Process actions here
    }
}
```
