### ISSUE TITLE
[Datasource]: Model config

### ISSUE THREAD

**Issue by khusseini** [khusseini/PimcoreRadBrickBundle#5]
Problem:
When fetching data for a view templates, most of the times, the view model used differs from data structures returned from Repositories or other services.

Proposed solution:
Add a `model` configuration to `areabricks.[areabrick].datasources.[datasource]` to describe a mapping from the data model to the view.

`config.yml`:
```yml
datasources:
  products_by_categories:
    service_id: app.repository.product
    method: findByCategories
      args:
      - categories
      - order_key: name
        order: ASC
areabricks:
  tabbed_categories:
    label: Categories shown in Tabs
    use_edit: true
    editables:
      select_categories:
        type: relations
        options:
          types: ['object']
          subtypes:
            object: object
          classes: ['CoreShopCategory']
    datasources:
      categories:
        id: products_by_categories
        args:
          categories: view["select_categories"].getElements() ?: []
        model:
          'each(categories, "category").getId()':
            id: 'category.getId()'
            label: 'category.getName()'
            products: 'products[category.getId()]'
```
- The `each()` function
    - creates a new context for each item in a collection with a given variable name
    - merges the new and old contexts to the evaluation
    - returns an array containing a model instead of a scalar value

Recursive example:
```yml
model:
  'each(categories, "category").getId()':
    id: 'category.getId()'
    label: 'category.getName()'
    products:
      'each(products[category.getId()], "product").getId()':
        id: product.getId()
        name: product.getName()
```
